package isabelle.query.regression

import isabelle.query.*
import java.nio.file.{Files, Path as JPath, Paths}
import TestSupport.*
import CliSupport.*

private[regression] object Cli_cli_prog_name {
  def run(): Unit = {
    disposition("test_cli_prog_name.BothNamesAreInstalled.test_both_names_are_declared", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.BothNamesAreInstalled.test_both_names_are_the_same_entry_point", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.BothNamesAreInstalled.test_the_alias_matches_the_distribution_name", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.NoHardcodedProgramName.test_no_message_hardcodes_the_canonical_name", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameFallsBackToCanonical.test_absent_argv_falls_back", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameFallsBackToCanonical.test_empty_argv0_falls_back", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameFallsBackToCanonical.test_module_path_falls_back", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameReflectsTheInvocation.test_a_renamed_wrapper_is_reported_as_itself", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameReflectsTheInvocation.test_each_console_script_name_is_reported_as_itself", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameReflectsTheInvocation.test_help_examples_name_the_invoked_command", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameReflectsTheInvocation.test_stderr_diagnostic_names_the_invoked_command", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameReflectsTheInvocation.test_subcommand_usage_inherits_the_invoked_command", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameReflectsTheInvocation.test_the_census_skip_notice_names_the_invoked_command", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameReflectsTheInvocation.test_usage_line_names_the_invoked_command", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
    disposition("test_cli_prog_name.ProgNameReflectsTheInvocation.test_version_line_names_the_invoked_command", "python-only", "Python console-script argv[0] reflection, argparse prog inheritance, Python source-import guard and pyproject packaging aliases; Scala is invoked through the fixed Isabelle tool name and has no sys.argv[0] API. Retain the original Python packaging/reference test.")
  }
}
