package isabelle.query.regression

import isabelle.query.*
import java.nio.file.{Files, Path as JPath, Paths}
import TestSupport.*
import CliSupport.*

private[regression] object Cli_namespace_cache {
  def run(): Unit = {
    disposition("test_namespace_cache.Augmented.test_no_build_when_session_heap_absent", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.Augmented.test_skips_when_session_is_base", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.Augmented.test_unions_base_and_session", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.CacheRoundTrip.test_load_missing_is_none", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.CacheRoundTrip.test_save_then_load", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.Fingerprint.test_changes_when_heap_changes", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.Fingerprint.test_empty_without_isabelle", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.Fingerprint.test_spawn_free", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.ProjectResolution.test_failed_dump_reports_committed_not_isabelle", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.ProjectResolution.test_forwards_dirs_to_dump", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.ProjectResolution.test_no_built_session_returns_committed", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.ProjectResolution.test_no_isabelle_returns_committed_without_glob", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.ProjectResolution.test_unions_committed_floor_with_built_sessions", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.Resolve.test_cache_hit_does_not_spawn", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.Resolve.test_cache_miss_regenerates_and_base_folds", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
    disposition("test_namespace_cache.Resolve.test_falls_back_to_committed", "python-only", "Python namespace-resolver JSON cache, fingerprint, built-heap subprocess/dump and module mocking mechanism; Scala uses compiled immutable namespace tables. Retain Python reference coverage; request-local namespace/root semantics are ported separately.")
  }
}
