package isabelle.query.regression

private[regression] object CliFixtures {
  val nested_THY = "theory Nested imports Main begin\n\nlemma flat: \"True\"\n  by simp\n\nlemma structured:\n  shows \"A\"\nproof -\n  have apos_1: \"A\"\n  proof -\n    have key: \"B\"\n    proof -\n      show \"B\" by blast\n    qed\n    show \"A\" using key by blast\n  qed\n  show \"A\" by (rule apos_1)\nqed\n\nlemma braced: \"C\"\nproof -\n  {\n    have inner: \"C\" by blast\n  }\n  show \"C\" by blast\nqed\n\nend\n"
  val owners_THY = "theory Owners imports Main begin\n\nsection \\<open>Widgets\\<close>\n\ndefinition widget :: nat where\n  \"widget = 42\"\n\nlemma size_bound:\n  assumes \"x > widget\"\n  shows \"x \\<noteq> 0\"\n  using assms by auto\n\nsection \\<open>More\\<close>\n\nlemma comm_add: \"a + b = b + (a::nat)\"\n  by simp\n\nend\n"
  val test_cli_context_flag_CONTEXT_DEFAULTS = Map("theory" -> 2, "outline" -> 2, "find" -> 2, "show" -> 2, "callers" -> 0)
  val test_cli_families_LOOKUP_LIST = List("show", "callees", "callers", "deps", "uses")
  val test_cli_families_SEARCH_PATHS = List("grep", "largest", "sorry")
  val test_cli_names_flag_NAMES_FLAG = List("theory", "defs", "find", "show", "callers", "callees", "grep", "methods")
  val test_cli_names_flag_NOOP_N = List("grep", "sorry")
  val test_cli_with_comments_PROSE_VERBS = List("find", "grep")
  val test_count_modes_THY = "theory T\nimports Main\nbegin\ndefinition d :: \"nat\" where \"d = 0\"\nlemma l: \"d = d\" by (simp add: d_def)\nend\n"
  val test_default_namespace_THY = "theory T imports Main begin\n\nlemma triv: \"(1::nat) + 1 = 2\"\n  by auto\n\nlemma structured: \"(2::nat) + 2 = 4\"\nproof -\n  have \"(2::nat) + 2 = 4\" by blast\n  thus ?thesis by metis\nqed\n\nend\n"
  val test_deps_qualified_TREE = Map("base/Substrate.thy" -> "theory Substrate imports Main begin\nlemma s_l: \"True\" by simp\nend\n", "ae/EncodingWrap.thy" -> "theory EncodingWrap\n  imports \"Proj_Base.Substrate\" \"HOL-Library.FuncSet\"\nbegin\nlemma e_l: \"True\" by simp\nend\n")
  val test_disambig_loci_BASE = "theory Base\nimports Main\nbegin\nlemma shared: \"True\" by simp\n\nlemma structured: \"True \\<and> True\"\nproof\n  show \"True\" by simp\n  show \"True\" by simp\nqed\nend\n"
  val test_disambig_loci_FILES = Map("alpha/ROOT" -> "session Alpha = HOL +\n  theories\n    Base\n    Examples\n", "alpha/Base.thy" -> "theory Base\nimports Main\nbegin\nlemma shared: \"True\" by simp\n\nlemma structured: \"True \\<and> True\"\nproof\n  show \"True\" by simp\n  show \"True\" by simp\nqed\nend\n", "alpha/Examples.thy" -> "theory Examples\nimports Base\nbegin\nlemma a_owner: \"True\" using shared by simp\nend\n", "beta/ROOT" -> "session Beta = HOL +\n  theories\n    Base\n    Examples\n", "beta/Base.thy" -> "theory Base\nimports Main\nbegin\nlemma shared: \"True\" by simp\n\nlemma structured: \"True \\<and> True\"\nproof\n  show \"True\" by simp\n  show \"True\" by simp\nqed\nend\n", "beta/Examples.thy" -> "theory Examples\nimports Base\nbegin\nlemma b_pad: \"True\" by simp\n\nlemma b_owner: \"True\" using shared by simp\n\nlemma b_after: \"True\" sorry\nend\n", "solo/ROOT" -> "session Solo = HOL +\n  theories\n    Base\n    Unique\n", "solo/Base.thy" -> "theory Base\nimports Main\nbegin\nlemma shared: \"True\" by simp\n\nlemma structured: \"True \\<and> True\"\nproof\n  show \"True\" by simp\n  show \"True\" by simp\nqed\nend\n", "solo/Unique.thy" -> "theory Unique\nimports Base\nbegin\nlemma only_one: \"True\" using shared by simp\nend\n")
  val test_disambig_names_THY = "theory {name}\nimports Main\nbegin\nlemma l{tag}: \"True\" by simp\nend\n"
  val test_disambig_names_FILES = Map("alpha/Examples.thy" -> "theory Examples\nimports Main\nbegin\nlemma l0: \"True\" by simp\nend\n", "beta/Examples.thy" -> "theory Examples\nimports Main\nbegin\nlemma l1: \"True\" by simp\nend\n", "alpha/Unique.thy" -> "theory Unique\nimports Main\nbegin\nlemma l2: \"True\" by simp\nend\n", "alpha/ROOT" -> "session Alpha = HOL +\n  theories\n    Examples\n    Unique\n", "beta/ROOT" -> "session Beta = HOL +\n  theories\n    Examples\n")
  val test_find_conjunction_SRC = Map("T" -> "theory T imports Main begin\nlemma length_of_encode_entry: \"True\" by simp\nlemma length_alone: \"True\" by simp\nlemma encode_entry_alone: \"True\" by simp\nrecord state =\n  rreqs :: \"nat set\"\nlemma stated: \"length xs = encode_entry ys\" by simp\nlemma stated_partly: \"length xs = 0\" by simp\nend\n", "U" -> "theory U imports Main begin\nlemma length_of_encode_entry_too: \"True\" by simp\nend\n")
  val test_heading_outline_HEAD = "theory T imports Main begin\n"
  val test_heading_outline_FOOT = "\nend\n"
  val test_heading_outline_ALL_SPELLINGS = "theory T imports Main begin\n\nchapter \\<open>Spaced ASCII cartouche\\<close>\nsection\\<open>No space before the cartouche\\<close>\nsubsection ‹Unicode cartouche›\n  subsubsection \\<open>Indented\\<close>\nparagraph \"Quoted string\"\nsubparagraph\n  \\<open>Split opener\\<close>\nlemma m: \"True\" by simp\n\nend\n"
  val test_heaps_dirs_VID = "Isabelle2099-9"
  val test_heaps_dirs_PLAT = "polyml-9.9.9_test-platform"
  val test_import_leaf_BASE = "theory Base\nimports Main\nbegin\ndefinition base :: \"nat\" where \"base = 0\"\nend\n"
  val test_import_leaf_LEAF = "theory Leaf\nimports \"../Base\"\nbegin\nlemma leaf_uses: \"base = base\" by simp\nend\n"
  val test_import_leaf_BARE = "theory Bare\nimports Leaf\nbegin\nlemma bare_uses: \"base = base\" by simp\nend\n"
  val test_import_leaf_ALIEN = "theory Alien\nimports \"../nowhere/Absent\" \"HOL-Library.FuncSet\"\nbegin\nlemma alien_uses: \"base = base\" by simp\nend\n"
  val test_import_leaf_A_TARGET = "theory A_Target\nimports Main\nbegin\ndefinition a_target :: \"nat\" where \"a_target = 0\"\nend\n"
  val test_import_leaf_B_TARGET = "theory B_Target\nimports Main\nbegin\ndefinition b_target :: \"nat\" where \"b_target = 0\"\nend\n"
  val test_import_leaf_A_DUP = "theory Dup\nimports A_Target\nbegin\nend\n"
  val test_import_leaf_B_DUP = "theory Dup\nimports B_Target\nbegin\nend\n"
  val test_import_leaf_CITE = "theory Cite\nimports Dup\nbegin\nlemma cites_a: \"a_target = a_target\" by simp\nlemma cites_b: \"b_target = b_target\" by simp\nend\n"
  val test_import_leaf_LEAF_FILES = Map("Base.thy" -> "theory Base\nimports Main\nbegin\ndefinition base :: \"nat\" where \"base = 0\"\nend\n", "Sub/Leaf.thy" -> "theory Leaf\nimports \"../Base\"\nbegin\nlemma leaf_uses: \"base = base\" by simp\nend\n", "Bare.thy" -> "theory Bare\nimports Leaf\nbegin\nlemma bare_uses: \"base = base\" by simp\nend\n", "Alien.thy" -> "theory Alien\nimports \"../nowhere/Absent\" \"HOL-Library.FuncSet\"\nbegin\nlemma alien_uses: \"base = base\" by simp\nend\n", "ROOT" -> "session Demo = HOL +\n  theories\n    Base\n    \"Sub/Leaf\"\n    Bare\n    Alien\n")
  val test_import_leaf_UNION_FILES = Map("alpha/A_Target.thy" -> "theory A_Target\nimports Main\nbegin\ndefinition a_target :: \"nat\" where \"a_target = 0\"\nend\n", "alpha/Dup.thy" -> "theory Dup\nimports A_Target\nbegin\nend\n", "alpha/Cite.thy" -> "theory Cite\nimports Dup\nbegin\nlemma cites_a: \"a_target = a_target\" by simp\nlemma cites_b: \"b_target = b_target\" by simp\nend\n", "alpha/ROOT" -> "session Alpha = HOL +\n  theories\n    A_Target\n    Dup\n    Cite\n", "beta/B_Target.thy" -> "theory B_Target\nimports Main\nbegin\ndefinition b_target :: \"nat\" where \"b_target = 0\"\nend\n", "beta/Dup.thy" -> "theory Dup\nimports B_Target\nbegin\nend\n", "beta/ROOT" -> "session Beta = HOL +\n  theories\n    B_Target\n    Dup\n")
  val test_largest_BIG = "theory Big imports Main begin\nlemma huge:\n  \"P x = P x\"\nproof -\n  have \"P x = P x\" by simp\n  then show ?thesis by simp\nqed\nend\n"
  val test_largest_SMALL = "theory Small imports Main begin\nlemma tiny: \"True\" by simp\nend\n"
  val test_layout_surface_PUBLIC = List(List("isabelle_layout", "SessionInfo"), List("isabelle_layout", "default_t_dir"), List("isabelle_layout", "discover_roots"), List("isabelle_layout", "iter_sessions"), List("isabelle_layout", "parse_root_sessions"), List("isabelle_layout", "parse_thy_imports"), List("isabelle_layout", "resolve_base_logic"), List("isabelle_layout", "resolve_session_theory"), List("isabelle_layout", "session_theories"), List("isabelle_layout.distribution", "is_known_nonhol_base"))
  val test_locus_format_CALLS = "theory Calls imports Main begin\n\nlemma foo: \"(0::nat) = 0\" by simp\n\nlemma bar:\n  \"(1::nat) = 1\"\n  using foo by simp\n\nend\n"
  val test_open_ranges_DEMO = "theory Demo imports Main begin\n\nlemma alpha: \"True\" by simp\n\nlemma beta: \"1 = 1\" by simp\n\ndefinition gamma :: nat where \"gamma = 3\"\n\nlemma delta: \"2 = 2\" by simp\n\nend\n"
  val test_preamble_attribution_THY = "theory Pre imports Main begin\n\ntext \\<open>Prose introducing the first lemma.\\<close>\n\nlemma alpha: \"P a\"\n  by simp\n\nlemma beta: \"P b\"\n  by simp\n\ntext \\<open>Prose introducing the third lemma.\\<close>\n\nlemma gamma: \"P c\"\n  by simp\n\nend\n"
  val test_search_patterns_THY = "theory Sym imports Main begin\nlocale split\\<^sub>i_tree =\n  fixes x :: nat\nbegin\nend\nlocale split\\<^sub>i_list =\n  fixes y :: nat\nbegin\nend\nlemma split\\<^sub>i_tree_smeq: \"True\" by simp\nlemma plain_name: \"True\" by simp\nlemma alpha\\<alpha>: \"True\" by simp\nend\n"
  val test_show_inline_proof_THY = "theory Show imports Main begin\n\nlemma one_liner: \"P a\" by simp\n\nlemma next_line: \"P b\"\n  by simp\n\nlemma shows_form:\n  assumes \"A g\"\n  shows \"P g\" by simp\n\nlemma term_line:\n  \"P c\" by auto\n\nlemma structured: \"P i\"\nproof -\n  have \"R i\" by simp\n  show \"P i\" by simp\nqed\n\nend\n"
  val test_statement_slice_THY = "theory Slice imports Main begin\n\ndefinition widget :: nat where\n  \"widget = 42\"\n\nlemma size_bound:\n  assumes \"x > widget\"\n  shows \"x \\<noteq> 0\"\n  using assms by auto\n\nlemma comm_add: \"a + b = b + (a::nat)\"\n  by simp\n\nend\n"
  val test_statement_slice_PROOF_LINE = "using assms by auto"
  val test_stdin_path_THY = "theory Demo imports Main begin\n\ntext \\<open>Prose mentioning foo, skipped by default.\\<close>\n\nlemma foo_bar: \"P x = P x\"\nproof -\n  have \"P x = P x\" by simp\n  show ?thesis sorry\nqed\n\nlemma baz: \"True\" by simp\n\nend\n"
  val test_theory_name_roundtrip_SRC = "theory Propositional\nimports Main\nbegin\n\nlemma triv: \\<open>True\\<close> by simp\n\nend\n"
  val test_theory_name_roundtrip_OTHER = "theory Plain\nimports Main\nbegin\n\nlemma also_triv: \\<open>True\\<close> by simp\n\nend\n"
}
