package isabelle.query.regression

object CliSuite {
  def run(): Unit = {
    Cli_bad_root.run()
    Cli_cli_context_flag.run()
    Cli_cli_families.run()
    Cli_cli_names_flag.run()
    Cli_cli_no_global_only_options.run()
    Cli_cli_prog_name.run()
    Cli_cli_root_flag.run()
    Cli_cli_version.run()
    Cli_cli_with_comments.run()
    Cli_closed_stdout.run()
    Cli_count_modes.run()
    Cli_default_namespace.run()
    Cli_deps_qualified.run()
    Cli_disambig_loci.run()
    Cli_disambig_names.run()
    Cli_enclosing.run()
    Cli_enclosing_blocks.run()
    Cli_find_conjunction.run()
    Cli_grep_window.run()
    Cli_heading_outline.run()
    Cli_heaps_dirs.run()
    Cli_import_leaf.run()
    Cli_largest.run()
    Cli_layout_surface.run()
    Cli_lines_forms.run()
    Cli_locus_format.run()
    Cli_namespace_cache.run()
    Cli_namespace_fallback.run()
    Cli_open_ranges.run()
    Cli_preamble_attribution.run()
    Cli_search_patterns.run()
    Cli_show_inline_proof.run()
    Cli_statement_slice.run()
    Cli_stdin_path.run()
    Cli_summary_aggregate.run()
    Cli_theory_name_roundtrip.run()
  }
}
