title = Isabelle/jEdit Query
module = $JEDIT_QUERY_JAR
requirements = \
  env:ISABELLE_SCALA_JAR \
  env:JEDIT_JARS \
  env:ISABELLE_QUERY_JAR
sources = \
  src/jedit_query_plugin.scala \
  src/query_word.scala \
  src/query_options.scala \
  src/query_index.scala \
  src/query_search.scala \
  src/query_editor.scala \
  src/query_navigate.scala \
  src/query_dockable.scala \
  src/query_context_menu.scala \
  src/query_actions.scala \
  src/query_plugin.scala
services = \
  isabelle.jedit_query.JEdit_Query_Plugin
