package isabelle.query.regression
import ParserValues.*
/** Assertion-for-assertion port of tests/test_marker_decl.py. Fixture literals retain source bytes. */
private[regression] object Parser_test_marker_decl {
private def h_TheHeadingFormsStillWork_sections(parent: Env, args: Vector[V], kw: Map[String,V]): V = {
val e = parent.clone()
e("text") = kw.getOrElse("text", args.lift(0).getOrElse(throw new IllegalArgumentException("missing text")))
return ParserBridge.call("parsing.extract_sections", Vector(e("text").invoke("splitlines", Vector(), Map())), Map())
V.none
}
private def case_MarkerGluedToKeyword_test_the_declaration_is_found_at_all(): Unit = TestSupport.test("test_marker_decl.MarkerGluedToKeyword.test_the_declaration_is_found_at_all") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("sec") = ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())
e("names") = ParserBridge.call("names", Vector(e("sec")), Map())
TestSupport.check(e("names").has(V("istopology")), "tests/test_marker_decl.py:103" + " actual=" + e("names"))
}
private def case_MarkerGluedToKeyword_test_a_marked_datatype_is_found(): Unit = TestSupport.test("test_marker_decl.MarkerGluedToKeyword.test_a_marked_datatype_is_found") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("sec") = ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())
e("names") = ParserBridge.call("names", Vector(e("sec")), Map())
TestSupport.check(e("names").has(V("colour")), "tests/test_marker_decl.py:106" + " actual=" + e("names"))
}
private def case_MarkerGluedToKeyword_test_the_entry_starts_on_its_own_line(): Unit = TestSupport.test("test_marker_decl.MarkerGluedToKeyword.test_the_entry_starts_on_its_own_line") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("sec") = ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())
e("names") = ParserBridge.call("names", Vector(e("sec")), Map())
e("e") = ParserBridge.call("next", Vector(V.seq(e("sec").field("entries").seq.flatMap { item => val c1 = e.clone(); c1("e") = item; if (V((c1("e").field("name").cmp("Eq", V("istopology")))).truth) Vector(c1("e")) else Vector.empty })), Map())
TestSupport.equal(e("e").field("thy_line"), V(7), "tests/test_marker_decl.py:110")
TestSupport.equal(e("e").field("tag"), V("DEF"), "tests/test_marker_decl.py:111")
}
private def case_MarkerInTheNameSlot_test_the_name_after_the_marker_is_taken(): Unit = TestSupport.test("test_marker_decl.MarkerInTheNameSlot.test_the_name_after_the_marker_is_taken") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("names") = ParserBridge.call("names", Vector(ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())), Map())
TestSupport.check(e("names").has(V("sets_final_sink'")), "tests/test_marker_decl.py:121" + " actual=" + e("names"))
}
private def case_MarkerInTheNameSlot_test_no_space_is_needed_after_the_close(): Unit = TestSupport.test("test_marker_decl.MarkerInTheNameSlot.test_no_space_is_needed_after_the_close") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("names") = ParserBridge.call("names", Vector(ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())), Map())
TestSupport.check(e("names").has(V("sets_Plus_algebra")), "tests/test_marker_decl.py:124" + " actual=" + e("names"))
}
private def case_MarkerInTheNameSlot_test_a_nested_cartouche_body_is_stepped_over(): Unit = TestSupport.test("test_marker_decl.MarkerInTheNameSlot.test_a_nested_cartouche_body_is_stepped_over") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("names") = ParserBridge.call("names", Vector(ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())), Map())
TestSupport.check(e("names").has(V("desharnais")), "tests/test_marker_decl.py:130" + " actual=" + e("names"))
}
private def case_MarkerInTheNameSlot_test_no_marker_is_indexed_as_a_name(): Unit = TestSupport.test("test_marker_decl.MarkerInTheNameSlot.test_no_marker_is_indexed_as_a_name") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("names") = ParserBridge.call("names", Vector(ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())), Map())
TestSupport.equal(V.seq(e("names").seq.flatMap { item => val c2 = e.clone(); c2("n") = item; if (V((c2("n").has(V("marker")))).truth) Vector(c2("n")) else Vector.empty }), vs(), "tests/test_marker_decl.py:133")
}
private def case_MarkerAfterTheName_test_the_name_stops_at_the_marker(): Unit = TestSupport.test("test_marker_decl.MarkerAfterTheName.test_the_name_stops_at_the_marker") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("names") = ParserBridge.call("names", Vector(ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())), Map())
TestSupport.check(e("names").has(V("lipschitzI_on")), "tests/test_marker_decl.py:143" + " actual=" + e("names"))
}
private def case_MarkerAfterTheName_test_every_declaration_is_found_exactly_once(): Unit = TestSupport.test("test_marker_decl.MarkerAfterTheName.test_every_declaration_is_found_exactly_once") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("names") = ParserBridge.call("names", Vector(ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())), Map())
TestSupport.equal(e("names"), vs(V("istopology"), V("sets_final_sink'"), V("sets_Plus_algebra"), V("desharnais"), V("lipschitzI_on"), V("colour")), "tests/test_marker_decl.py:146")
}
private def case_MarkerBodyIsNotLiveSource_test_the_body_is_blanked(): Unit = TestSupport.test("test_marker_decl.MarkerBodyIsNotLiveSource.test_the_body_is_blanked") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("sec") = ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())
e("live") = V("\n").invoke("join", Vector(e("sec").invoke("live_source", Vector(), Map())), Map())
TestSupport.check(!e("live").has(V("Desharnais")), "tests/test_marker_decl.py:159" + " actual=" + e("live"))
TestSupport.check(!e("live").has(V("contributor")), "tests/test_marker_decl.py:160" + " actual=" + e("live"))
}
private def case_MarkerBodyIsNotLiveSource_test_the_tag_word_is_blanked(): Unit = TestSupport.test("test_marker_decl.MarkerBodyIsNotLiveSource.test_the_tag_word_is_blanked") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("sec") = ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())
e("live") = V("\n").invoke("join", Vector(e("sec").invoke("live_source", Vector(), Map())), Map())
TestSupport.check(!e("live").has(V("important")), "tests/test_marker_decl.py:165" + " actual=" + e("live"))
}
private def case_MarkerBodyIsNotLiveSource_test_the_marker_is_not_recorded_as_a_note(): Unit = TestSupport.test("test_marker_decl.MarkerBodyIsNotLiveSource.test_the_marker_is_not_recorded_as_a_note") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("sec") = ParserBridge.call("section_from", Vector(e("MARKED"), V("Marked")), Map())
e("live") = V("\n").invoke("join", Vector(e("sec").invoke("live_source", Vector(), Map())), Map())
val unpack3 = ParserBridge.call("parsing.scan_regions", Vector(e("MARKED").invoke("splitlines", Vector(), Map())), Map("want_inner" -> V(true))); TestSupport.equal(unpack3.seq.size, 4, "unpack arity"); e("_spans") = unpack3.at(V(0)); e("notes") = unpack3.at(V(1)); e("_inner") = unpack3.at(V(2)); e("_open") = unpack3.at(V(3))
TestSupport.equal(e("notes"), vm(), "tests/test_marker_decl.py:173")
}
private def case_MarkedHeading_test_the_heading_is_in_the_outline(): Unit = TestSupport.test("test_marker_decl.MarkedHeading.test_the_heading_is_in_the_outline") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("found") = ParserBridge.call("parsing.extract_sections", Vector(e("MARKED").invoke("splitlines", Vector(), Map())), Map())
TestSupport.check(e("found").has(vs(V("subsection"), V("Supremum Norm"), V(5))), "tests/test_marker_decl.py:186" + " actual=" + e("found"))
}
private def case_TheHeadingFormsStillWork_test_the_plain_form(): Unit = TestSupport.test("test_marker_decl.TheHeadingFormsStillWork.test_the_plain_form") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

TestSupport.equal(h_TheHeadingFormsStillWork_sections(e, Vector(V("section \\<open>Plain\\<close>")), Map()), vs(vs(V("section"), V("Plain"), V(1))), "tests/test_marker_decl.py:198")
}
private def case_TheHeadingFormsStillWork_test_the_quoted_title_form(): Unit = TestSupport.test("test_marker_decl.TheHeadingFormsStillWork.test_the_quoted_title_form") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

TestSupport.equal(h_TheHeadingFormsStillWork_sections(e, Vector(V("subsection \"Quoted\"")), Map()), vs(vs(V("subsection"), V("Quoted"), V(1))), "tests/test_marker_decl.py:203")
}
private def case_TheHeadingFormsStillWork_test_the_unicode_cartouche_form(): Unit = TestSupport.test("test_marker_decl.TheHeadingFormsStillWork.test_the_unicode_cartouche_form") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

TestSupport.equal(h_TheHeadingFormsStillWork_sections(e, Vector(V("chapter ‹Uni›")), Map()), vs(vs(V("chapter"), V("Uni"), V(1))), "tests/test_marker_decl.py:207")
}
private def case_TheHeadingFormsStillWork_test_no_space_before_the_opener(): Unit = TestSupport.test("test_marker_decl.TheHeadingFormsStillWork.test_no_space_before_the_opener") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

TestSupport.equal(h_TheHeadingFormsStillWork_sections(e, Vector(V("paragraph\\<open>Tight\\<close>")), Map()), vs(vs(V("paragraph"), V("Tight"), V(1))), "tests/test_marker_decl.py:211")
}
private def case_TheHeadingFormsStillWork_test_an_indented_heading(): Unit = TestSupport.test("test_marker_decl.TheHeadingFormsStillWork.test_an_indented_heading") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

TestSupport.equal(h_TheHeadingFormsStillWork_sections(e, Vector(V("   subsubsection \\<open>In\\<close>")), Map()), vs(vs(V("subsubsection"), V("In"), V(1))), "tests/test_marker_decl.py:215")
}
private def case_TheHeadingFormsStillWork_test_the_split_form(): Unit = TestSupport.test("test_marker_decl.TheHeadingFormsStillWork.test_the_split_form") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

TestSupport.equal(h_TheHeadingFormsStillWork_sections(e, Vector(V("section\n  \\<open>Split\\<close>")), Map()), vs(vs(V("section"), V("Split"), V(1))), "tests/test_marker_decl.py:220")
}
private def case_TheHeadingFormsStillWork_test_a_longer_word_does_not_lead_with_a_heading(): Unit = TestSupport.test("test_marker_decl.TheHeadingFormsStillWork.test_a_longer_word_does_not_lead_with_a_heading") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

TestSupport.equal(h_TheHeadingFormsStillWork_sections(e, Vector(V("sections \\<open>No\\<close>")), Map()), vs(), "tests/test_marker_decl.py:227")
}
private def case_TheHeadingFormsStillWork_test_a_bare_word_with_no_title_is_not_a_heading(): Unit = TestSupport.test("test_marker_decl.TheHeadingFormsStillWork.test_a_bare_word_with_no_title_is_not_a_heading") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

TestSupport.equal(h_TheHeadingFormsStillWork_sections(e, Vector(V("section\nlemma foo: \"True\"")), Map()), vs(), "tests/test_marker_decl.py:230")
}
private def case_TheAlreadyRedactedMarkersStillWork_test_a_comment_note_is_still_recorded(): Unit = TestSupport.test("test_marker_decl.TheAlreadyRedactedMarkersStillWork.test_a_comment_note_is_still_recorded") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("sec") = ParserBridge.call("section_from", Vector(e("UNMARKED"), V("Plain")), Map())
e("names") = ParserBridge.call("names", Vector(e("sec")), Map())
val unpack4 = ParserBridge.call("parsing.scan_regions", Vector(e("UNMARKED").invoke("splitlines", Vector(), Map())), Map("want_inner" -> V(true))); TestSupport.equal(unpack4.seq.size, 4, "unpack arity"); e("_spans") = unpack4.at(V(0)); e("notes") = unpack4.at(V(1)); e("_inner") = unpack4.at(V(2)); e("_open") = unpack4.at(V(3))
TestSupport.check(e("notes").truth, "tests/test_marker_decl.py:243")
}
private def case_TheAlreadyRedactedMarkersStillWork_test_cancelled_text_declares_nothing(): Unit = TestSupport.test("test_marker_decl.TheAlreadyRedactedMarkersStillWork.test_cancelled_text_declares_nothing") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("sec") = ParserBridge.call("section_from", Vector(e("UNMARKED"), V("Plain")), Map())
e("names") = ParserBridge.call("names", Vector(e("sec")), Map())
TestSupport.check(!e("names").has(V("ghost")), "tests/test_marker_decl.py:246" + " actual=" + e("names"))
}
private def case_TheAlreadyRedactedMarkersStillWork_test_every_declaration_is_found(): Unit = TestSupport.test("test_marker_decl.TheAlreadyRedactedMarkersStillWork.test_every_declaration_is_found") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("sec") = ParserBridge.call("section_from", Vector(e("UNMARKED"), V("Plain")), Map())
e("names") = ParserBridge.call("names", Vector(e("sec")), Map())
TestSupport.equal(e("names"), vs(V("split\\<^sub>i_tree"), V("\\<phi>step"), V("annotated"), V("cancelled")), "tests/test_marker_decl.py:249")
}
private def case_MarkupNamesStillWork_test_a_subscripted_name_is_one_name(): Unit = TestSupport.test("test_marker_decl.MarkupNamesStillWork.test_a_subscripted_name_is_one_name") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("names") = ParserBridge.call("names", Vector(ParserBridge.call("section_from", Vector(e("UNMARKED"), V("Plain")), Map())), Map())
TestSupport.check(e("names").has(V("split\\<^sub>i_tree")), "tests/test_marker_decl.py:261" + " actual=" + e("names"))
}
private def case_MarkupNamesStillWork_test_a_greek_leading_name_is_one_name(): Unit = TestSupport.test("test_marker_decl.MarkupNamesStillWork.test_a_greek_leading_name_is_one_name") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("names") = ParserBridge.call("names", Vector(ParserBridge.call("section_from", Vector(e("UNMARKED"), V("Plain")), Map())), Map())
TestSupport.check(e("names").has(V("\\<phi>step")), "tests/test_marker_decl.py:264" + " actual=" + e("names"))
}
private def case_MarkupNamesStillWork_test_a_user_pattern_still_escapes_every_markup_token(): Unit = TestSupport.test("test_marker_decl.MarkupNamesStillWork.test_a_user_pattern_still_escapes_every_markup_token") {
val e: Env = scala.collection.mutable.Map.empty
e("MARKED") = V("theory Marked\nimports Main\nbegin\n\nsubsection\\<^marker>\\<open>tag unimportant\\<close> \\<open>Supremum Norm\\<close>\n\ndefinition\\<^marker>\\<open>tag important\\<close> istopology :: \"bool \\<Rightarrow> bool\"\n  where \"istopology x = x\"\n\nlemma \\<^marker>\\<open>tag important\\<close> sets_final_sink': \"True\" by simp\n\nlemma \\<^marker>\\<open>tag important\\<close>sets_Plus_algebra: \"True\" by simp\n\nlemma \\<^marker>\\<open>contributor \\<open>Martin Desharnais\\<close>\\<close> desharnais: \"True\"\n  by simp\n\ndefinition lipschitzI_on\\<^marker>\\<open>tag important\\<close> :: \"bool\"\n  where \"lipschitzI_on = True\"\n\ndatatype\\<^marker>\\<open>tag unimportant\\<close> colour = Red | Green\n\nend\n")
e("UNMARKED") = V("theory Plain\nimports Main\nbegin\n\ndefinition split\\<^sub>i_tree :: \"bool\" where \"split\\<^sub>i_tree = True\"\n\ndefinition \\<phi>step :: \"bool\" where \"\\<phi>step = True\"\n\nlemma annotated: \"True\" \\<comment> \\<open>a marginal note\\<close>\n  by simp\n\nlemma cancelled: \"True\" \\<^cancel>\\<open>lemma ghost: \"False\"\\<close>\n  by simp\n\nend\n")

e("names") = ParserBridge.call("names", Vector(ParserBridge.call("section_from", Vector(e("UNMARKED"), V("Plain")), Map())), Map())
TestSupport.equal(ParserBridge.call("_user_pattern", Vector(V("\\<open>")), Map()), ParserBridge.call("re.escape", Vector(V("\\<open>")), Map()), "tests/test_marker_decl.py:271")
TestSupport.equal(ParserBridge.call("_user_pattern", Vector(V("a\\<^sub>1")), Map()), V("a").plus(ParserBridge.call("re.escape", Vector(V("\\<^sub>")), Map())).plus(V("1")), "tests/test_marker_decl.py:272")
}
def run(): Unit = { case_MarkerGluedToKeyword_test_the_declaration_is_found_at_all(); case_MarkerGluedToKeyword_test_a_marked_datatype_is_found(); case_MarkerGluedToKeyword_test_the_entry_starts_on_its_own_line(); case_MarkerInTheNameSlot_test_the_name_after_the_marker_is_taken(); case_MarkerInTheNameSlot_test_no_space_is_needed_after_the_close(); case_MarkerInTheNameSlot_test_a_nested_cartouche_body_is_stepped_over(); case_MarkerInTheNameSlot_test_no_marker_is_indexed_as_a_name(); case_MarkerAfterTheName_test_the_name_stops_at_the_marker(); case_MarkerAfterTheName_test_every_declaration_is_found_exactly_once(); case_MarkerBodyIsNotLiveSource_test_the_body_is_blanked(); case_MarkerBodyIsNotLiveSource_test_the_tag_word_is_blanked(); case_MarkerBodyIsNotLiveSource_test_the_marker_is_not_recorded_as_a_note(); case_MarkedHeading_test_the_heading_is_in_the_outline(); case_TheHeadingFormsStillWork_test_the_plain_form(); case_TheHeadingFormsStillWork_test_the_quoted_title_form(); case_TheHeadingFormsStillWork_test_the_unicode_cartouche_form(); case_TheHeadingFormsStillWork_test_no_space_before_the_opener(); case_TheHeadingFormsStillWork_test_an_indented_heading(); case_TheHeadingFormsStillWork_test_the_split_form(); case_TheHeadingFormsStillWork_test_a_longer_word_does_not_lead_with_a_heading(); case_TheHeadingFormsStillWork_test_a_bare_word_with_no_title_is_not_a_heading(); case_TheAlreadyRedactedMarkersStillWork_test_a_comment_note_is_still_recorded(); case_TheAlreadyRedactedMarkersStillWork_test_cancelled_text_declares_nothing(); case_TheAlreadyRedactedMarkersStillWork_test_every_declaration_is_found(); case_MarkupNamesStillWork_test_a_subscripted_name_is_one_name(); case_MarkupNamesStillWork_test_a_greek_leading_name_is_one_name(); case_MarkupNamesStillWork_test_a_user_pattern_still_escapes_every_markup_token() }
}
