"""Corpus constant names for the width var/const classifier (bucket c).
GENERATED by scripts/harvest_corpus_constants.py — do not edit by hand.

Provenance:
    Corpus:       AFP (Isabelle2025-2)
    Sample:       159 entries >= 10000 lines
    Thresholds:   free-DF >= 20, bound-fraction <= 0.15
    Extracted:    2026-07-19
    Constants:    73

A name lands here when it appears FREE across many unrelated AFP entries yet is
almost never BOUND — the signature of a shared constant (HOL/Main, common
libraries) as opposed to a conventional free variable (`xs`, `n`), which recurs
just as widely but is frequently bound.  See the harvester for the rationale.
"""

CORPUS_CONSTANTS = frozenset({
    'Collect', 'False', 'Inl', 'Inr', 'List', 'Max', 'Min', 'None', 'Pair',
    'Pow', 'Some', 'Suc', 'True', 'UNIV', 'Var', 'abs', 'bij_betw',
    'butlast', 'card', 'concat', 'distinct', 'div', 'dom', 'drop', 'dvd',
    'empty', 'filter', 'finite', 'fold', 'foldl', 'foldr', 'fst', 'hd', 'id',
    'infinite', 'inj', 'inj_on', 'insert', 'int', 'inv', 'inverse', 'last',
    'length', 'list', 'list_all', 'map', 'map_of', 'map_option', 'max',
    'measure', 'min', 'mod', 'nat', 'norm', 'o', 'range', 'real',
    'real_of_int', 'replicate', 'res', 'rev', 'set', 'size', 'snd', 'sorted',
    'sqrt', 'sum', 'sum_list', 'take', 'tl', 'undefined', 'wf', 'zip',
})
