"""Committed notation table: operator glyph -> canonical Isabelle constant.

GENERATED by scripts/extract_notation.py (resolved once from the HOL-Analysis
heap).  Do not edit by hand.  Consumed by shape.const_canon_est as a pure-Python
lookup (no Isabelle at runtime) — the method-table pattern; a glyph absent
here falls back to itself, so the map is an approximation that only ever
canonicalises, never loses, a constant.
"""

NOTATION = {
    '*': 'Groups.times_class.times',
    '+': 'Groups.plus_class.plus',
    '-': 'Groups.minus_class.minus',
    '/': 'Rings.divide_class.divide',
    '<': 'Orderings.ord_class.less',
    '=': 'HOL.eq',
    '>': 'Orderings.ord_class.less',
    '@': 'List.append',
    '\\<Longrightarrow>': 'Pure.imp',
    '\\<and>': 'HOL.conj',
    '\\<circ>': 'Fun.comp',
    '\\<equiv>': 'Pure.eq',
    '\\<ge>': 'Orderings.ord_class.less_eq',
    '\\<i>': 'Complex.imaginary_unit',
    '\\<in>': 'Set.member',
    '\\<int>': 'Int.ring_1_class.Ints',
    '\\<inter>': 'Lattices.inf_class.inf',
    '\\<le>': 'Orderings.ord_class.less_eq',
    '\\<longleftrightarrow>': 'HOL.eq',
    '\\<longlongrightarrow>': 'Filter.filterlim',
    '\\<longrightarrow>': 'HOL.implies',
    '\\<nat>': 'Nat.semiring_1_class.Nats',
    '\\<noteq>': 'HOL.Not',
    '\\<notin>': 'HOL.Not',
    '\\<or>': 'HOL.disj',
    '\\<rat>': 'Rat.field_char_0_class.Rats',
    '\\<real>': 'Real_Vector_Spaces.Reals',
    '\\<subset>': 'Orderings.ord_class.less',
    '\\<subseteq>': 'Orderings.ord_class.less_eq',
    '\\<supset>': 'Orderings.ord_class.less',
    '\\<supseteq>': 'Orderings.ord_class.less_eq',
    '\\<times>': 'Product_Type.Sigma',
    '\\<union>': 'Lattices.sup_class.sup',
}
