#!/bin/sh
# Extract definitions, lemmas, theorems, axioms, datatypes, records, and type synonyms
# from all .thy files and write a compact lemma registry.
#
# Usage: ./scripts/update-registry.sh [output_file]
# Default output: memory lemma-registry.md

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ISA_DIR="$(dirname "$SCRIPT_DIR")"
MEMORY_DIR="$HOME/.claude/projects/-Users-as456-projects-ndtht/memory"
OUTPUT="${1:-$MEMORY_DIR/lemma-registry.md}"

# Theory build order (from ROOT file)
THEORIES="Asymptotics Pairing Size Preliminaries NTM3 Encoding3 NTM FiniteModification Enumeration Coverage DiagonalLang LemmaA LemmaB MainTheorem"

{
  echo "# Lemma Registry — NDTHT Formalization"
  echo ""
  echo "Auto-generated by \`isa/scripts/update-registry.sh\` on $(date +%Y-%m-%d)."
  echo ""

  for thy in $THEORIES; do
    file="$ISA_DIR/$thy.thy"
    if [ ! -f "$file" ]; then
      continue
    fi

    echo "## $thy.thy"
    echo '```'

    # Extract key declarations (one line each, no proof bodies)
    # Replace keyword with tag, stripping the original keyword
    sed -n '
      /^datatype /{ s/^datatype /DATATYPE /; s/ where$//; p; }
      /^type_synonym /{ s/^type_synonym /TYPE /; p; }
      /^record /{ s/^record /RECORD /; p; }
      /^fun /{ s/^fun /FUN /; p; }
      /^primrec /{ s/^primrec /FUN /; p; }
      /^definition /{ s/^definition /DEF /; s/ where$//; p; }
      /^lemma /{ s/^lemma /LEMMA /; p; }
      /^theorem /{ s/^theorem /THEOREM /; p; }
      /^axiomatization /{ s/^axiomatization.*/AXIOMATIZATION/; p; }
      /^  [a-z_]*:$/{ s/^  /  AXIOM /; p; }
    ' "$file"

    echo '```'
    echo ""
  done
} > "$OUTPUT"

echo "Registry written to $OUTPUT"
echo "$(grep -c '^\(DEF\|FUN\|LEMMA\|THEOREM\|AXIOM\|RECORD\|DATATYPE\|TYPE\)' "$OUTPUT" 2>/dev/null || echo 0) entries"
