#!/bin/sh
# Extract definitions, lemmas, theorems, axioms, datatypes, records, and type synonyms
# from all .thy files listed in ROOT and write a compact lemma registry.
#
# Usage: ./scripts/update-registry.sh [output_file]
# Default output: memory lemma-registry.md

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ISA_DIR="$(dirname "$SCRIPT_DIR")"
MEMORY_DIR="$HOME/.claude/projects/-Users-as456-projects-ndtht/memory"
OUTPUT="${1:-$MEMORY_DIR/lemma-registry.md}"

# Get theory list from ROOT file
ROOT_FILE="$ISA_DIR/ROOT"
if [ ! -f "$ROOT_FILE" ]; then
  echo "ERROR: no ROOT file in $ISA_DIR" >&2
  exit 1
fi

# Parse theories from ROOT (between "theories" and "document_files" lines)
THEORIES=$(awk '
  /^[[:space:]]*theories/ { in_theories = 1; next }
  /^[[:space:]]*(document_files|sessions|options|description)/ { in_theories = 0 }
  in_theories && /^[[:space:]]+[A-Za-z_][A-Za-z0-9_]*/ {
    gsub(/^[[:space:]]+/, "")
    gsub(/[[:space:]]+$/, "")
    if ($0 != "") print $0
  }
' "$ROOT_FILE")

{
  echo "# Lemma Registry — NDTHT Formalization"
  echo ""
  echo "Auto-generated by \`isa/scripts/update-registry.sh\` on $(date +%Y-%m-%d)."
  echo ""

  echo "$THEORIES" | while IFS= read -r thy; do
    file="$ISA_DIR/$thy.thy"
    if [ ! -f "$file" ]; then
      continue
    fi

    echo "## $thy.thy"
    echo '```'

    # Extract key declarations (one line each, no proof bodies)
    # Replace keyword with tag, stripping the original keyword
    sed -n '
      /^datatype /{ s/^datatype /DATATYPE /; s/ where$//; p; }
      /^type_synonym /{ s/^type_synonym /TYPE /; p; }
      /^record /{ s/^record /RECORD /; p; }
      /^fun /{ s/^fun /FUN /; p; }
      /^primrec /{ s/^primrec /FUN /; p; }
      /^definition /{ s/^definition /DEF /; s/ where$//; p; }
      /^lemma /{ s/^lemma /LEMMA /; p; }
      /^theorem /{ s/^theorem /THEOREM /; p; }
      /^axiomatization /{ s/^axiomatization.*/AXIOMATIZATION/; p; }
      /^  [a-z_]*:$/{ s/^  /  AXIOM /; p; }
    ' "$file"

    echo '```'
    echo ""
  done
} > "$OUTPUT"

echo "Registry written to $OUTPUT"
echo "$(grep -c '^\(DEF\|FUN\|LEMMA\|THEOREM\|AXIOM\|RECORD\|DATATYPE\|TYPE\)' "$OUTPUT" 2>/dev/null || echo 0) entries"
