#!/usr/bin/env python3
"""Harvest the operator-symbol glyphs a corpus uses and resolve each to its
canonical Isabelle constant, writing the committed notation table
``src/isabelle_query/_notation.py``.

Reproduced once, checked in, consumed at runtime as a pure-Python dict — the
method-table pattern, no Isabelle on the query path.  The glyph *set* is
harvested from usage (the ``_corpus_constants`` philosophy: what real proofs
write), so the table covers what ``const_canon_est`` meets; the *resolution* is
the operator-section parse ``(GLYPH)`` -> head ``Const`` via one ``ML_process``
pass (``scripts/_dump_notation.ML``).

    python3 scripts/extract_notation.py ~/repos/afp/thys \
        --session HOL-Analysis --theory Complex_Main

Without ``--session`` it resolves against the plain ``HOL`` / ``Main`` heap (core
operators only); a richer session (``HOL-Analysis`` loads ``Complex_Main``)
resolves analysis notation too.  A glyph the heap does not know resolves to the
empty constant and is dropped from the committed map, so ``const_canon_est``
falls back to the raw glyph for it — exactly like an un-harvested corpus
constant, and documented as such.
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from isabelle_query import parsing, shape  # noqa: E402

_ISABELLE = (os.environ.get("ISABELLE_TOOL")
             or "/Applications/Isabelle2025-2.app/bin/isabelle")
_ML = Path(__file__).resolve().parent / "_dump_notation.ML"
_OUT = (Path(__file__).resolve().parent.parent / "src" / "isabelle_query"
        / "_notation.py")


def _entry_dirs(root: Path) -> list[Path]:
    """The census-consistent unit directories under ``root`` (every immediate
    subdir with a ``ROOT``, else ``root`` itself) — the same walk the census and
    ``fanin_idf`` use, so the harvest sees exactly the census's proofs."""
    subs = sorted(d for d in root.iterdir()
                  if d.is_dir() and (d / "ROOT").is_file())
    return subs if subs else [root]


def harvest_glyphs(roots: list[Path]) -> set[str]:
    """Distinct operator-symbol glyphs in every structured proof's goal-step
    statements across ``roots`` — exactly the tokens ``shape._is_operator_const``
    accepts, i.e. what ``const_canon_est`` will canonicalise.  Per-entry parse
    failures are local (skipped), like the census."""
    glyphs: set[str] = set()
    for root in roots:
        root = root.expanduser().resolve()
        for entry_dir in _entry_dirs(root):
            sections: list = []
            try:
                parsing._sections_from_dir(entry_dir, set(), sections)
            except (OSError, ValueError, IndexError, RecursionError):
                continue
            for sec in sections:
                try:
                    sec.source()
                except (OSError, ValueError, IndexError):
                    continue
                for e in sec.entries:
                    try:
                        steps = shape._scan_steps(sec, e)
                    except (OSError, ValueError, IndexError, RecursionError):
                        continue
                    for s in steps:
                        if s.kind == "goal" and s.stmt_text:
                            for t in shape._stmt_tokens(s.stmt_text):
                                if shape._is_operator_const(t):
                                    glyphs.add(t)
    return glyphs


def resolve(glyphs: set[str], session: str,
            theory: str | None) -> dict[str, str]:
    """Resolve each glyph to its canonical head constant via one ML pass; a glyph
    that does not parse as ``(GLYPH)`` is omitted."""
    env = dict(os.environ)
    env["QUERY_NOTATION_GLYPHS"] = "\n".join(sorted(glyphs))
    if theory:
        env["QUERY_NOTATION_THEORY"] = theory
    cmd = [_ISABELLE, "ML_process", "-l", session, "-r", "-f", str(_ML)]
    proc = subprocess.run(cmd, capture_output=True, text=True, env=env,
                          timeout=600)
    out: dict[str, str] = {}
    for line in proc.stdout.splitlines():
        if line.startswith("NOTATION\t"):
            _tag, glyph, const = line.split("\t", 2)
            if const:
                out[glyph] = const
    return out


def write_table(mapping: dict[str, str], session: str) -> None:
    body = "\n".join(f"    {g!r}: {c!r}," for g, c in sorted(mapping.items()))
    _OUT.write_text(
        '"""Committed notation table: operator glyph -> canonical Isabelle '
        "constant.\n\n"
        "GENERATED by scripts/extract_notation.py (resolved once from the "
        f"{session}\nheap).  Do not edit by hand.  Consumed by "
        "shape.const_canon_est as a pure-Python\nlookup (no Isabelle at "
        "runtime) — the method-table pattern; a glyph absent\nhere falls back "
        'to itself, so the map is an approximation that only ever\n'
        'canonicalises, never loses, a constant.\n"""\n\n'
        f"NOTATION = {{\n{body}\n}}\n")


def main(argv: list[str]) -> int:
    roots: list[Path] = []
    session, theory = "HOL", None
    it = iter(argv)
    for a in it:
        if a == "--session":
            session = next(it)
        elif a == "--theory":
            theory = next(it)
        else:
            roots.append(Path(a))
    if not roots:
        roots = [Path("~/repos/afp/thys")]
    glyphs = harvest_glyphs(roots)
    print(f"harvested {len(glyphs)} distinct operator glyphs", file=sys.stderr)
    mapping = resolve(glyphs, session, theory)
    print(f"resolved {len(mapping)}/{len(glyphs)} to a constant", file=sys.stderr)
    write_table(mapping, session)
    print(f"wrote {_OUT} ({len(mapping)} entries)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
