#!/usr/bin/env python3
r"""Corpus probe: prose blocks whose OPENER the scanner does not recognise.

[txt-prose] fixed one missing prose command (`txt`).  Judging the residue of
`probe_method_coverage.py` afterwards turned up two more ways for a prose block
to go unrecognised — neither about *which* command, both about the shape of its
opening line:

  * **split opener** — the command word alone on its line, the cartouche on the
    next:

        text
          \<open>We have developed two points of view on freeness:
        \<^item> being generated by a code.
        \<close>

    `TEXT_OPEN_RE` needs both on one line, and `_find_balanced_close` begins its
    depth count *on* the opening line, so even a widened pattern would return a
    one-line block and leave the prose live.  (Combinatorics_Words/Submonoids.thy
    :2696 — its "generated **by a** code" is where the token `a` came from.)

  * **wrapped heading** — a `section`/`subsection` cartouche that closes on a
    later line.  Headings are not in `text_blocks` at all, so a wrapped one
    leaves its continuation lines live.  (Smith_Normal_Form/Diagonal_To_Smith.thy
    :1172 — "transform the input matrix **by means** of elementary operations"
    is where `means` came from.)

The number that matters is not the residue, though.  A prose word only shows up
there if it is *not* in the method table; when the leaked word happens to be a
real method name — `cases`, `rule`, `induct`, `simp`, `assumption` are all
ordinary English — it is silently counted as a method use **today**, inflating
`query methods` and the shape census with no residue entry to notice.  So this
counts both: the tokens that would become false positives once
[introducer-no-table] lands, and the ones already miscounted.

Usage:  probe_prose_openers.py [N_ENTRIES] [--show N]
"""
import os
import re
import sys
from collections import Counter
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if not os.environ.get("PYTHONPATH"):
    sys.path.insert(0, str(_ROOT / "src"))

from isabelle_query import cli, graph  # noqa: E402

AFP = Path.home() / "repos" / "afp" / "thys"
_args = sys.argv[1:]
SHOW = 0
if "--show" in _args:
    i = _args.index("--show")
    SHOW = int(_args[i + 1])
    del _args[i:i + 2]
LIMIT = int(_args[0]) if _args else 10_000

# The command word alone on its line — nothing after it but whitespace.
_SPLIT_OPEN_RE = re.compile(r"^\s*(text|text_raw|txt)\s*$")
# A heading, with its cartouche opening on the same line.
_HEADING_RE = re.compile(
    r"^\s*(chapter|section|subsection|subsubsection)\s*(?:\\<open>|‹)")
_OPEN_RE = re.compile(r"\\<open>|‹")
_CLOSE_RE = re.compile(r"\\<close>|›")
_DISCHARGE_RE = re.compile(r"\b(?:by|apply)\b\s*\(?\s*([\w']+)")

tot: Counter = Counter()
fp_tokens: Counter = Counter()      # leaked words that are NOT methods
miscounted: Counter = Counter()     # leaked words that ARE in the table
samples: list[str] = []


def _close_line(lines, start):
    """0-indexed line where the cartouche opened at/after `start` closes."""
    depth = 0
    for n in range(start, len(lines)):
        depth += len(_OPEN_RE.findall(lines[n]))
        depth -= len(_CLOSE_RE.findall(lines[n]))
        if depth <= 0 and n > start:
            return n
        if depth <= 0 and n == start and _OPEN_RE.search(lines[n]):
            return n
    return start


def _charge(kind, lines, live, lo, hi, theory, known):
    """Tally the prose lines in [lo, hi] (0-indexed) that a scanner still reads.

    The test is membership of `known` — the lines covered by `sec.text_blocks`,
    which is what feeds `graph._noise_spans` — NOT whether `live_source()` shows
    them.  `live_source` deliberately never blanks a document block (it redacts
    only what the tokenizer reports, and a block is introduced by a command), so
    measuring it would report every fix here as having changed nothing.
    """
    for n in range(lo, min(hi + 1, len(lines))):
        if n in known or n >= len(live) or not live[n].strip():
            continue
        tot[f"{kind}_live_lines"] += 1
        m = _DISCHARGE_RE.search(live[n])
        if not m:
            continue
        tok = m.group(1)
        tot[f"{kind}_discharge"] += 1
        if tok in graph._PROOF_METHODS:
            miscounted[tok] += 1
            tot[f"{kind}_miscounted"] += 1
        else:
            fp_tokens[tok] += 1
        if len(samples) < SHOW:
            samples.append(f"  [{kind}] {theory}:{n + 1} tok={tok!r} "
                           f"in_table={tok in graph._PROOF_METHODS}\n"
                           f"      {lines[n].strip()[:110]}")


for ent in sorted(d for d in AFP.iterdir() if d.is_dir())[:LIMIT]:
    for thy_path in sorted(ent.rglob("*.thy")):
        try:
            sec = cli._parse_one(thy_path.stem, thy_path)
        except Exception as exc:  # noqa: BLE001
            tot["parse_failures"] += 1
            continue
        raw, live = sec.source(), sec.live_source()
        known = set()
        for a, b in sec.text_blocks:
            known.update(range(a - 1, b))
        n = 0
        while n < len(raw):
            if _SPLIT_OPEN_RE.match(raw[n]) and n + 1 < len(raw) \
                    and _OPEN_RE.search(raw[n + 1]):
                end = _close_line(raw, n + 1)
                tot["split_blocks"] += 1
                tot["split_lines"] += end - n + 1
                _charge("split", raw, live, n, end, sec.theory, known)
                n = end + 1
                continue
            if _HEADING_RE.match(raw[n]):
                end = _close_line(raw, n)
                if end > n:                       # wraps past its own line
                    tot["heading_blocks"] += 1
                    tot["heading_lines"] += end - n + 1
                    _charge("heading", raw, live, n + 1, end, sec.theory, known)
                    n = end + 1
                    continue
            n += 1

print(f"entries scanned: up to {LIMIT}")
if tot["parse_failures"]:
    print(f"!! parse failures: {tot['parse_failures']} — not a measurement")
print(f"\nsplit openers (`text` then \\<open> on the next line): "
      f"{tot['split_blocks']} blocks / {tot['split_lines']} lines")
print(f"  lines a scanner still reads:     {tot['split_live_lines']}")
print(f"  carrying a by/apply introducer:  {tot['split_discharge']}")
print(f"    …token IS in the table (miscounted today): {tot['split_miscounted']}")
print(f"\nwrapped headings (section cartouche closing on a later line): "
      f"{tot['heading_blocks']} blocks / {tot['heading_lines']} lines")
print(f"  continuation lines still read:   {tot['heading_live_lines']}")
print(f"  carrying a by/apply introducer:  {tot['heading_discharge']}")
print(f"    …token IS in the table (miscounted today): "
      f"{tot['heading_miscounted']}")
print(f"\nwould-be false positives (token not a method): "
      f"{sum(fp_tokens.values())} occurrences / {len(fp_tokens)} distinct")
for tok, c in fp_tokens.most_common(12):
    print(f"    {tok:28} {c}")
print(f"\nMISCOUNTED TODAY (token is a real method name in English prose): "
      f"{sum(miscounted.values())} occurrences / {len(miscounted)} distinct")
for tok, c in miscounted.most_common(12):
    print(f"    {tok:28} {c}")
if samples:
    print("\nsamples:")
    print("\n".join(samples))
