title = Isabelle Query
module = $ISABELLE_QUERY_JAR
requirements = \
  env:ISABELLE_SCALA_JAR
sources = \
  src/py_text.scala \
  src/namespace.scala \
  src/model.scala \
  src/regions.scala \
  src/entries.scala \
  src/discovery.scala \
  src/theory.scala \
  src/output.scala \
  src/render.scala \
  src/usage_graph.scala \
  src/commands.scala \
  src/usage.scala \
  src/sites.scala \
  src/shape_data.scala \
  src/shape.scala \
  src/shape_cmds.scala \
  src/cli.scala \
  src/server.scala \
  src/delegate.scala \
  src/query_tool.scala
services = \
  isabelle.query.Query_Tools \
  isabelle.query.Query_Server_Commands
